 

	{"statusCode":0,"statusDesc":"success","errorCode":0,"title":"Error","contactId":"e23214f601261000d89cf12434253c04","updatedDate":"Feb 7, 2011","firstName":"#DATA","lastName":"","displayName":"#DATA","photo":false,"photoUrl":"","prefModeOfComm":"","orgName":"","jobTitle":"","source":"mbpim","buddyuserid":"","buddyStatus":"","buddyMDN":"","starred":false,"ics":"","userId":"","handset":true,"middleName":"","nickName":"","relationship":"","gender":"","orgUnit":"","namePrefix":"","nameSuffix":"","anniversary":"","spouse":"","children":"","note":"","profession":"","assistant":"","maritalStatus":"","updatedTimestamp":1297114120830,"timeZone":"","birthday":"","avatarId":"","avatarName":"","groups":[],"mobileGroups":[{"id":"1001","name":"mbSync"}],"phones":{"mobile":[{"number":"#3282","index":1,"carrier":""}]},"addresses":{},"emails":{},"webpages":{},"ims":[],"endPointAssoc":[]}
