


{"serviceInfo":[{"jobId":"091d9e92-a446-43b6-9f75-7a444958463e","endPointId":4,"serviceId":1,"userEndpointId":0,"loginUserName":"caoyu88@gmail.com"},{"jobId":"33c2d9b5-f9bc-4674-abc9-2aa1f8ec5dfa","endPointId":2,"serviceId":1,"userEndpointId":0,"loginUserName":"cy7188@yahoo.com"},{"jobId":"27137ad0-480d-4dc3-9e66-d98d9ef5fa84","endPointId":3,"serviceId":1,"userEndpointId":0,"loginUserName":"caoyu88@hotmail.com"}],"statusCode":0,"statusDesc":"success"}