{
	"all":{
			"All": 716,
			"music": 3,
			"pictures": 15,
			"videos": 3,
			"documents": 2
		},
	"flags":{
			"errorMessage": "",
			"showSyncPod": false
		},
	"tags": [],
	"numRows":23,
	"numDummyRows":3,
	"statusCode":0,
	"statusDesc":"successful",
	"folderPath": "My Files &gt; Family",
	"items": [
		{	"fileId": "",
		"fileName": "",
		"type": "dummy",
		"fileSize": "",
		"fileExt": "",
		"uploadDateShortTxt": "Today, July 15th, 2011 Friday",
		"filePreviewIcon": "",
		"fileUrl": ""
		},
		{	"fileId": "1010001",
		"fileName": "picture_00001.jpg",
		"type": "Picture",
		"fileSize": "14K",
		"fileExt": "jpg",
		"uploadDateShortTxt": "Mon, 03:16 PM",
		"filePreviewIcon": "../simulation/vmm/GLTE.jpg",
		"fileUrl": "../simulation/vmm/GLTE.jpg"
		},
		{	"fileId": "/Family/2011",
		"fileName": "2011",
		"type": "folder",
		"fileSize": "914M",
		"fileExt": "",
		"uploadDateShortTxt": "Mon, 02:16 PM",
		"filePreviewIcon": "../simulation/vmm/rootFolder",
		"fileUrl": "../simulation/vmm/rootFolder"
		},
		{	"fileId": "/Family/2009",
		"fileName": "2009",
		"type": "folder",
		"fileSize": "914M",
		"fileExt": "",
		"uploadDateShortTxt": "Mon, 02:16 PM",
		"filePreviewIcon": "../simulation/vmm/rootFolder",
		"fileUrl": "../simulation/vmm/rootFolder"
		},
		{	"fileId": "/Family/2005",
		"fileName": "Old2005",
		"type": "folder",
		"fileSize": "914M",
		"fileExt": "",
		"uploadDateShortTxt": "Mon, 02:16 PM",
		"filePreviewIcon": "../simulation/vmm/rootFolder",
		"fileUrl": "../simulation/vmm/rootFolder"
		},
		{	"fileId": "1010017",
		"fileName": "document_00017",
		"type": "Document",
		"fileSize": "112K",
		"fileExt": "jpg",
		"uploadDateShortTxt": "Mon, 03:16 PM",
		"filePreviewIcon": "../simulation/inbox/vzw-htc.jpg",
		"fileUrl": "../simulation/inbox/vzw-htc.jpg"
		},
		{	"fileId": "1010018",
		"fileName": "test.swf",
		"type": "Video",
		"fileSize": "212K",
		"fileExt": "swf",
		"uploadDateShortTxt": "Mon, 03:26 PM",
		"filePreviewIcon": "../simulation/vmm/test.swf",
		"fileUrl": "../simulation/vmm/test.swf"
		},
		{	"fileId": "1010019",
		"fileName": "Waltz.mp3",
		"type": "Music",
		"fileSize": "312K",
		"fileExt": "mp3",
		"uploadDateShortTxt": "Mon, 03:46 PM",
		"filePreviewIcon": "../simulation/vmm/Waltz.mp3",
		"fileUrl": "../simulation/vmm/Waltz.mp3"
		},
		{	"fileId": "1010020",
		"fileName": "example.swf",
		"type": "Video",
		"fileSize": "112K",
		"fileExt": "swf",
		"uploadDateShortTxt": "Mon, 03:16 PM",
		"filePreviewIcon": "../simulation/vmm/example.swf",
		"fileUrl": "../simulation/vmm/example.swf"
		},
		{	"fileId": "1010021",
		"fileName": "picture_00021",
		"type": "Picture",
		"fileSize": "112K",
		"fileExt": "jpg",
		"uploadDateShortTxt": "Mon, 03:16 PM",
		"filePreviewIcon": "../simulation/inbox/vzw-iphone.png",
		"fileUrl": "../simulation/inbox/vzw-iphone.png"
		},
		{	"fileId": "1010022",
		"fileName": "picture_00022",
		"type": "Picture",
		"fileSize": "112K",
		"fileExt": "jpg",
		"uploadDateShortTxt": "Mon, 03:16 PM",
		"filePreviewIcon": "../simulation/inbox/vzw-300x224.jpg",
		"fileUrl": "../simulation/inbox/vzw-300x224.jpg"
		},
		{	"fileId": "1010023",
		"fileName": "Chevy.flv",
		"type": "Video",
		"fileSize": "112K",
		"fileExt": "flv",
		"uploadDateShortTxt": "Thu, 03:16 PM",
		"filePreviewIcon": "../simulation/vmm/Chevy.flv",
		"fileUrl": "../simulation/vmm/Chevy.flv"
		},
		{	"fileId": "1010024",
		"fileName": "chevyjump.mp4",
		"type": "Video",
		"fileSize": "112K",
		"fileExt": "mp4",
		"uploadDateShortTxt": "Thu, 03:16 PM",
		"filePreviewIcon": "../simulation/vmm/chevyjump.mp4",
		"fileUrl": "../simulation/vmm/chevyjump.mp4"
		},
		{	"fileId": "1010026",
		"fileName": "oceans-clip.mp4",
		"type": "Video",
		"fileSize": "212K",
		"fileExt": "mp4",
		"uploadDateShortTxt": "Fri, 04:16 PM",
		"filePreviewIcon": "http://video-js.zencoder.com/oceans-clip.mp4",
		"fileUrl": "http://video-js.zencoder.com/oceans-clip.mp4"
		},
		{	"fileId": "1010027",
		"fileName": "oceans-clip.webm",
		"type": "Video",
		"fileSize": "312K",
		"fileExt": "webm",
		"uploadDateShortTxt": "Fri, 04:26 PM",
		"filePreviewIcon": "http://video-js.zencoder.com/oceans-clip.webm",
		"fileUrl": "http://video-js.zencoder.com/oceans-clip.webm"
		},
		{	"fileId": "1010028",
		"fileName": "oceans-clip.ogv",
		"type": "Video",
		"fileSize": "412K",
		"fileExt": "ogv",
		"uploadDateShortTxt": "Fri, 04:36 PM",
		"filePreviewIcon": "http://video-js.zencoder.com/oceans-clip.ogv",
		"fileUrl": "http://video-js.zencoder.com/oceans-clip.ogv"
		},
		{	"fileId": "1010025",
		"fileName": "flowplayer.swf",
		"type": "Video",
		"fileSize": "112K",
		"fileExt": "swf",
		"uploadDateShortTxt": "Fri, 03:16 PM",
		"filePreviewIcon": "../simulation/vmm/flowplayer.swf",
		"fileUrl": "../simulation/vmm/flowplayer.swf"
		},
		{	"fileId": "1010002",
		"fileName": "video_00002.3g2",
		"type": "Video",
		"fileSize": "28K",
		"fileExt": "3g2",
		"uploadDateShortTxt": "Mon, 03:16 PM",
		"filePreviewIcon": "../simulation/vmm/sample_3GPP2.3g2",
		"fileUrl": "../simulation/vmm/sample_3GPP2.3g2"
		},
		{	"fileId": "1010003",
		"fileName": "music_00003.wav",
		"type": "Music",
		"fileSize": "345K",
		"fileExt": "wav",
		"uploadDateShortTxt": "Mon, 03:16 PM",
		"filePreviewIcon": "../simulation/vmm/wavfile.wav",
		"fileUrl": "h../simulation/vmm/wavfile.wav"
		},
		{	"fileId": "1010004",
		"fileName": "document_00004",
		"type": "Document",
		"fileSize": "112K",
		"fileExt": "jpg",
		"uploadDateShortTxt": "Mon, 03:16 PM",
		"filePreviewIcon": "../simulation/inbox/lte-modems-_1.jpg",
		"fileUrl": "../simulation/inbox/lte-modems-_1.jpg"
		},
		{	"fileId": "",
		"fileName": "",
		"type": "dummy",
		"fileSize": "",
		"fileExt": "",
		"uploadDateShortTxt": "Yesterday, July 14th, 2011 Thursday",
		"filePreviewIcon": "",
		"fileUrl": ""
		},
		{	"fileId": "1010006",
		"fileName": "picture_00006",
		"type": "Picture",
		"fileSize": "112K",
		"fileExt": "jpg",
		"uploadDateShortTxt": "Mon, 03:16 PM",
		"filePreviewIcon": "http://ad.wsodcdn.com/8bec9b10877d5d7fd7c0fb6e6a631357/120x60_Peel_Logo.png",
		"fileUrl": "http://ad.wsodcdn.com/8bec9b10877d5d7fd7c0fb6e6a631357/120x60_Peel_Logo.png"
		},
		{	"fileId": "1010007",
		"fileName": "chevyjump.mov",
		"type": "Video",
		"fileSize": "1344K",
		"fileExt": "mov",
		"uploadDateShortTxt": "Mon, 03:16 PM",
		"filePreviewIcon": "../simulation/vmm/chevyjump.mov",
		"fileUrl": "../simulation/vmm/chevyjump.mov"
		},
		{	"fileId": "1010008",
		"fileName": "chevyjump.avi",
		"type": "Video",
		"fileSize": "330K",
		"fileExt": "avi",
		"uploadDateShortTxt": "Mon, 03:16 PM",
		"filePreviewIcon": "../simulation/vmm/chevyjump.avi",
		"fileUrl": "../simulation/vmm/chevyjump.avi"
		},
		{	"fileId": "1010009",
		"fileName": "chevyjump.mpg",
		"type": "Video",
		"fileSize": "836K",
		"fileExt": "mpg",
		"uploadDateShortTxt": "Mon, 03:16 PM",
		"filePreviewIcon": "../simulation/vmm/chevyjump.mpg",
		"fileUrl": "../simulation/vmm/chevyjump.mpg"
		},
		{	"fileId": "1010010",
		"fileName": "starsight.wav",
		"type": "Music",
		"fileSize": "36K",
		"fileExt": "wav",
		"uploadDateShortTxt": "Mon, 03:16 PM",
		"filePreviewIcon": "../simulation/vmm/starsight.wav",
		"fileUrl": "../simulation/vmm/starsight.wav"
		},
		{	"fileId": "1010011",
		"fileName": "midnightrider.mid",
		"type": "Music",
		"fileSize": "23K",
		"fileExt": "mid",
		"uploadDateShortTxt": "Mon, 03:16 PM",
		"filePreviewIcon": "../simulation/vmm/midnightrider.mid",
		"fileUrl": "../simulation/vmm/midnightrider.mid"
		},
		{	"fileId": "1010012",
		"fileName": "ba.swf",
		"type": "Video",
		"fileSize": "112K",
		"fileExt": "swf",
		"uploadDateShortTxt": "Mon, 03:16 PM",
		"filePreviewIcon": "http://localhost:9080/ics/simulation/vmm/BA.swf",
		"fileUrl": "http://localhost:9080/ics/simulation/vmm/BA.swf"
		},
		{	"fileId": "1010013",
		"fileName": "video_00013",
		"type": "Video",
		"fileSize": "212K",
		"fileExt": "mp4",
		"uploadDateShortTxt": "Mon, 03:16 PM",
		"filePreviewIcon": "../simulation/vmm/chevyjump.mp4",
		"fileUrl": "../simulation/vmm/chevyjump.mp4"
		},
		{	"fileId": "",
		"fileName": "",
		"type": "dummy",
		"fileSize": "",
		"fileExt": "",
		"uploadDateShortTxt": "July 9th, 2011 Saturday",
		"filePreviewIcon": "",
		"fileUrl": ""
		},
		{	"fileId": "1010014",
		"fileName": "picture_00014",
		"type": "Picture",
		"fileSize": "112K",
		"fileExt": "jpg",
		"uploadDateShortTxt": "Mon, 03:16 PM",
		"filePreviewIcon": "../simulation/inbox/skype-vzw-commercial-dl.png",
		"fileUrl": "../simulation/inbox/skype-vzw-commercial-dl.png"
		},
		{	"fileId": "1010015",
		"fileName": "video_00015",
		"type": "Video",
		"fileSize": "112K",
		"fileExt": "jpg",
		"uploadDateShortTxt": "Mon, 03:16 PM",
		"filePreviewIcon": "../simulation/inbox/Verizon-Launches.jpg",
		"fileUrl": "../simulation/inbox/Verizon-Launches.jpg"
		},
		{	"fileId": "1010016",
		"fileName": "picture_00016",
		"type": "Picture",
		"fileSize": "112K",
		"fileExt": "jpg",
		"uploadDateShortTxt": "Mon, 03:16 PM",
		"filePreviewIcon": "../simulation/inbox/verizon10.jpg",
		"fileUrl": "../simulation/inbox/verizon10.jpg"
		}
		
	],
	"notifications": []
}
