{
    "identity":"id",
    "statusCode":0,
    "statusDesc":"Music Playlists fetched successfully",
    "numRows":16,
    "items":[
    	{
            "id":255000,
            "type":"music",
            "name":"Rock"
        },
        {
            "id":955000,
            "type":"music",
            "name":"Rap"
        },
        {
            "id":555000,
            "type":"music",
            "name":"Hip"
        },
        {
            "id":455000,
            "type":"music",
            "name":"TestMusic1"
        },
        {
            "id":255111,
            "type":"videos",
            "name":"Romantic"
        },
        {
            "id":955111,
            "type":"videos",
            "name":"Action"
        },
        {
            "id":555111,
            "type":"videos",
            "name":"Comedy"
        },
        {
            "id":455111,
            "type":"videos",
            "name":"TestVideos2"
        },
        {
            "id":255222,
            "type":"pictures",
            "name":"Friends"
        },
        {
            "id":955222,
            "type":"pictures",
            "name":"Family"
        },
        {
            "id":555222,
            "type":"pictures",
            "name":"Classmates"
        },
        {
            "id":455222,
            "type":"pictures",
            "name":"TestPictures3"
        },
        {
            "id":255333,
            "type":"documents",
            "name":"myFolder1"
        },
        {
            "id":955333,
            "type":"documents",
            "name":"Technology"
        },
        {
            "id":555333,
            "type":"documents",
            "name":"Health"
        },
        {
            "id":455333,
            "type":"documents",
            "name":"TestDocuments4"
        }
    ]
}