<textarea>
	{"statusCode":0,"statusDesc":"Attachment uploaded successfully!","title":"","flexXmlResponse":"&lt;response&gt;&lt;composerId&gt;1329493046116&lt;/composerId&gt;&lt;statusCode&gt;0&lt;/statusCode&gt;&lt;statusDesc&gt;Attachment uploaded successfully!&lt;/statusDesc&gt;&lt;title&gt;null&lt;/title&gt;&lt;attachPath&gt;/s1/1_VDO_Video_28kb_sample.3gp&lt;/attachPath&gt;&lt;attachName&gt;1_VDO_Video_28kb_sample.3gp&lt;/attachName&gt;&lt;attachSize&gt;27.89&lt;/attachSize&gt;&lt;duration&gt;0&lt;/duration&gt;&lt;/response&gt;"}
</textarea>