{"attachPath":"/s1/1_IMG_0000-bald-eag.jpg","attachName":"1_IMG_0000-bald-eag.jpg","attachmentSize":58152,"attachmentSizeWithUnits":"56KB","totalAttachmentSize":58152,"statusCode":0,"statusDesc":"Successfully uploaded attachment","title":""}
