{
    "getContactsTime":0,
    "getMessageTime":1884,
    "numRows":9,
    "numDummyRows":7,
    "all":{
        "All":124,
        "email":85,
        "sms":29,
        "mms":10,
        "vvm":0,
        "call_log":0
    },
    "unread":{
        "All":42,
        "email":42,
        "sms":0,
        "mms":0,
        "vvm":0,
        "call_log":0
    },
    "undelivered":{
        "smsRowNums":0,
        "mmsRowNums":0,
        "isShow":false,
        "smsItems":[],
        "mmsItems":[]
    },
    "statusCode":0,
    "statusDesc":"Done",
    "items":[{
            "messageId":0,
            "folderName":"",
            "type":6,
            "isThread":false,
            "threadLength":0,
            "draftLength":0,
            "deliveryStatusCode":0,
            "from":[],
            "to":[],
            "toParty":[],
            "cc":[],
            "subject":"Today, February 02nd, 2012 Thursday",
            "receivedDateShortTxt":"",
            "receivedDate":"",
            "contactId":"",
            "attachment":false,
            "size":0,
            "priority":0,
            "answered":false,
            "draft":false,
            "read":false,
            "sourceSystem":"",
            "sourceMessageId":"",
            "sourceMessageFolder":"",
            "sourceMessageUID":"",
            "isStarred":false,
            "inNetwork":false,
            "isBuddy":false,
            "ics":"",
            "sensitivity":"",
            "orderNum":0,
            "tags":[]
        },
        {
            "messageId":385,
            "folderName":"UnifiedInbox",
            "type":1,
            "isThread":false,
            "threadLength":0,
            "draftLength":0,
            "deliveryStatusCode":0,
            "from":[{
                    "name":"Li, Hui",
                    "emailAddress":"Hui.Li3@VerizonWireless.com"
                }
            ],
            "to":[{
                    "name":"",
                    "emailAddress":"buaplus@gmail.com"
                }
            ],
            "toParty":[],
            "cc":[],
            "subject":"test attachment",
            "receivedDateShortTxt":"Today, 09:29 AM",
            "receivedDate":"Thu Feb 02 09:29:47 EST 2012",
            "contactId":"",
            "attachment":true,
            "size":51,
            "priority":3,
            "answered":false,
            "draft":false,
            "read":true,
            "sourceSystem":"GOOGLE",
            "sourceMessageId":"<4f2a9e05.1446650a.159f.ffffdd01SMTPIN_ADDED@mx.google.com>",
            "sourceMessageFolder":"INBOX",
            "sourceMessageUID":"11",
            "isStarred":false,
            "inNetwork":false,
            "isBuddy":false,
            "ics":"",
            "sensitivity":"",
            "orderNum":1,
            "tags":[]
        },
        {
            "messageId":0,
            "folderName":"",
            "type":6,
            "isThread":false,
            "threadLength":0,
            "draftLength":0,
            "deliveryStatusCode":0,
            "from":[],
            "to":[],
            "toParty":[],
            "cc":[],
            "subject":"Yesterday, February 01st, 2012 Wednesday",
            "receivedDateShortTxt":"",
            "receivedDate":"",
            "contactId":"",
            "attachment":false,
            "size":0,
            "priority":0,
            "answered":false,
            "draft":false,
            "read":false,
            "sourceSystem":"",
            "sourceMessageId":"",
            "sourceMessageFolder":"",
            "sourceMessageUID":"",
            "isStarred":false,
            "inNetwork":false,
            "isBuddy":false,
            "ics":"",
            "sensitivity":"",
            "orderNum":0,
            "tags":[]
        },
        {
            "messageId":257,
            "folderName":"Drafts",
            "type":1,
            "isThread":true,
            "threadLength":2,
            "draftLength":1,
            "deliveryStatusCode":0,
            "from":[{
                    "name":"",
                    "emailAddress":"buaplus@gmail.com"
                },
                {
                    "name":"Mrs. Safia Gaddafi",
                    "emailAddress":"safia.f.gaddafi@lybiafirstlady.net"
                }
            ],
            "to":[{
                    "name":"",
                    "emailAddress":"buaplus@gmail.com"
                },
                {
                    "name":"",
                    "emailAddress":"safia.f.gaddafi@lybiafirstlady.net"
                }
            ],
            "toParty":[],
            "cc":[],
            "subject":"Re:Business letter attched",
            "receivedDateShortTxt":"Wed, 10:30 AM",
            "receivedDate":"Wed Feb 01 10:30:55 EST 2012",
            "contactId":"",
            "attachment":true,
            "size":20,
            "priority":3,
            "answered":false,
            "draft":false,
            "read":true,
            "sourceSystem":"GOOGLE",
            "sourceMessageId":"",
            "sourceMessageFolder":"",
            "sourceMessageUID":"",
            "isStarred":false,
            "inNetwork":false,
            "isBuddy":false,
            "ics":"",
            "sensitivity":"",
            "orderNum":1,
            "tags":[]
        },
        {
            "messageId":0,
            "folderName":"",
            "type":6,
            "isThread":false,
            "threadLength":0,
            "draftLength":0,
            "deliveryStatusCode":0,
            "from":[],
            "to":[],
            "toParty":[],
            "cc":[],
            "subject":"January 27th, 2012 Friday",
            "receivedDateShortTxt":"",
            "receivedDate":"",
            "contactId":"",
            "attachment":false,
            "size":0,
            "priority":0,
            "answered":false,
            "draft":false,
            "read":false,
            "sourceSystem":"",
            "sourceMessageId":"",
            "sourceMessageFolder":"",
            "sourceMessageUID":"",
            "isStarred":false,
            "inNetwork":false,
            "isBuddy":false,
            "ics":"",
            "sensitivity":"",
            "orderNum":0,
            "tags":[]
        },
        {
            "messageId":382,
            "folderName":"UnifiedInbox",
            "type":1,
            "isThread":false,
            "threadLength":0,
            "draftLength":0,
            "deliveryStatusCode":0,
            "from":[{
                    "name":"Google",
                    "emailAddress":"privacy-noreply@google.com"
                }
            ],
            "to":[{
                    "name":"",
                    "emailAddress":"buaplus@gmail.com"
                }
            ],
            "toParty":[],
            "cc":[],
            "subject":"Changes to Google Privacy Policy and Terms of Service",
            "receivedDateShortTxt":"Fri, 04:24 PM",
            "receivedDate":"Fri Jan 27 16:24:46 EST 2012",
            "contactId":"",
            "attachment":false,
            "size":10,
            "priority":3,
            "answered":false,
            "draft":false,
            "read":false,
            "sourceSystem":"GOOGLE",
            "sourceMessageId":"<2012.01.24.privacy@notifications.google.com>",
            "sourceMessageFolder":"INBOX",
            "sourceMessageUID":"10",
            "isStarred":false,
            "inNetwork":false,
            "isBuddy":false,
            "ics":"",
            "sensitivity":"",
            "orderNum":1,
            "tags":[]
        },
        {
            "messageId":383,
            "folderName":"UnifiedInbox",
            "type":1,
            "isThread":false,
            "threadLength":0,
            "draftLength":0,
            "deliveryStatusCode":0,
            "from":[{
                    "name":"Li, Hui",
                    "emailAddress":"Hui.Li3@VerizonWireless.com"
                }
            ],
            "to":[{
                    "name":"",
                    "emailAddress":"buaplus@gmail.com"
                }
            ],
            "toParty":[],
            "cc":[],
            "subject":"test2 from li3",
            "receivedDateShortTxt":"Fri, 12:10 PM",
            "receivedDate":"Fri Jan 27 12:10:42 EST 2012",
            "contactId":"",
            "attachment":false,
            "size":4,
            "priority":3,
            "answered":false,
            "draft":false,
            "read":true,
            "sourceSystem":"GOOGLE",
            "sourceMessageId":"<4f22e280.0a56650a.662b.12dbSMTPIN_ADDED@mx.google.com>",
            "sourceMessageFolder":"INBOX",
            "sourceMessageUID":"9",
            "isStarred":false,
            "inNetwork":false,
            "isBuddy":false,
            "ics":"",
            "sensitivity":"",
            "orderNum":1,
            "tags":[]
        },
        {
            "messageId":0,
            "folderName":"",
            "type":6,
            "isThread":false,
            "threadLength":0,
            "draftLength":0,
            "deliveryStatusCode":0,
            "from":[],
            "to":[],
            "toParty":[],
            "cc":[],
            "subject":"January 17th, 2012 Tuesday",
            "receivedDateShortTxt":"",
            "receivedDate":"",
            "contactId":"",
            "attachment":false,
            "size":0,
            "priority":0,
            "answered":false,
            "draft":false,
            "read":false,
            "sourceSystem":"",
            "sourceMessageId":"",
            "sourceMessageFolder":"",
            "sourceMessageUID":"",
            "isStarred":false,
            "inNetwork":false,
            "isBuddy":false,
            "ics":"",
            "sensitivity":"",
            "orderNum":0,
            "tags":[]
        },
        {
            "messageId":278,
            "folderName":"UnifiedInbox",
            "type":1,
            "isThread":true,
            "threadLength":4,
            "draftLength":0,
            "deliveryStatusCode":0,
            "from":[{
                    "name":"Mail Delivery Subsystem",
                    "emailAddress":"mailer-daemon@googlemail.com"
                }
            ],
            "to":[{
                    "name":"",
                    "emailAddress":"buaplus@gmail.com"
                },
                {
                    "name":"",
                    "emailAddress":"buaplus@gmail.com"
                }
            ],
            "toParty":[],
            "cc":[],
            "subject":"Delivery Status Notification (Failure)",
            "receivedDateShortTxt":"Tue, 08:29 PM",
            "receivedDate":"Tue Jan 17 20:29:04 EST 2012",
            "contactId":"",
            "attachment":false,
            "size":2,
            "priority":3,
            "answered":false,
            "draft":false,
            "read":true,
            "sourceSystem":"GOOGLE",
            "sourceMessageId":"",
            "sourceMessageFolder":"",
            "sourceMessageUID":"",
            "isStarred":false,
            "inNetwork":false,
            "isBuddy":false,
            "ics":"",
            "sensitivity":"",
            "orderNum":1,
            "tags":[]
        },
        {
            "messageId":0,
            "folderName":"",
            "type":6,
            "isThread":false,
            "threadLength":0,
            "draftLength":0,
            "deliveryStatusCode":0,
            "from":[],
            "to":[],
            "toParty":[],
            "cc":[],
            "subject":"November 28th, 2011 Monday",
            "receivedDateShortTxt":"",
            "receivedDate":"",
            "contactId":"",
            "attachment":false,
            "size":0,
            "priority":0,
            "answered":false,
            "draft":false,
            "read":false,
            "sourceSystem":"",
            "sourceMessageId":"",
            "sourceMessageFolder":"",
            "sourceMessageUID":"",
            "isStarred":false,
            "inNetwork":false,
            "isBuddy":false,
            "ics":"",
            "sensitivity":"",
            "orderNum":0,
            "tags":[]
        },
        {
            "messageId":160,
            "folderName":"Drafts",
            "type":1,
            "isThread":true,
            "threadLength":21,
            "draftLength":1,
            "deliveryStatusCode":0,
            "from":[{
                    "name":"",
                    "emailAddress":"MAILER-DAEMON@yahoo.com"
                },
                {
                    "name":"",
                    "emailAddress":"buaplus@gmail.com"
                },
                {
                    "name":"",
                    "emailAddress":"MAILER-DAEMON@yahoo.com"
                }
            ],
            "to":[{
                    "name":"",
                    "emailAddress":"MAILER-DAEMON@yahoo.com"
                },
                {
                    "name":"",
                    "emailAddress":"icstesting@yahoo.com"
                },
                {
                    "name":"",
                    "emailAddress":"icstesting@yahoo.com"
                }
            ],
            "toParty":[],
            "cc":[],
            "subject":"Re:Delivery failure",
            "receivedDateShortTxt":"Mon, 02:04 PM",
            "receivedDate":"Mon Nov 28 14:04:25 EST 2011",
            "contactId":"",
            "attachment":false,
            "size":4,
            "priority":3,
            "answered":false,
            "draft":false,
            "read":true,
            "sourceSystem":"GOOGLE",
            "sourceMessageId":"",
            "sourceMessageFolder":"",
            "sourceMessageUID":"",
            "isStarred":true,
            "inNetwork":false,
            "isBuddy":false,
            "ics":"",
            "sensitivity":"",
            "orderNum":1,
            "tags":[{
                    "id":1000,
                    "name":"Starred"
                }
            ]
        },
        {
            "messageId":0,
            "folderName":"",
            "type":6,
            "isThread":false,
            "threadLength":0,
            "draftLength":0,
            "deliveryStatusCode":0,
            "from":[],
            "to":[],
            "toParty":[],
            "cc":[],
            "subject":"November 21st, 2011 Monday",
            "receivedDateShortTxt":"",
            "receivedDate":"",
            "contactId":"",
            "attachment":false,
            "size":0,
            "priority":0,
            "answered":false,
            "draft":false,
            "read":false,
            "sourceSystem":"",
            "sourceMessageId":"",
            "sourceMessageFolder":"",
            "sourceMessageUID":"",
            "isStarred":false,
            "inNetwork":false,
            "isBuddy":false,
            "ics":"",
            "sensitivity":"",
            "orderNum":0,
            "tags":[]
        },
        {
            "messageId":218,
            "folderName":"UnifiedInbox",
            "type":1,
            "isThread":false,
            "threadLength":0,
            "draftLength":0,
            "deliveryStatusCode":0,
            "from":[{
                    "name":"Gmail Team",
                    "emailAddress":"mail-noreply@google.com"
                }
            ],
            "to":[{
                    "name":"bua plus",
                    "emailAddress":"buaplus@gmail.com"
                }
            ],
            "toParty":[],
            "cc":[],
            "subject":"Import your contacts and old email",
            "receivedDateShortTxt":"Mon, 03:06 PM",
            "receivedDate":"Mon Nov 21 15:06:54 EST 2011",
            "contactId":"",
            "attachment":false,
            "size":3,
            "priority":3,
            "answered":false,
            "draft":false,
            "read":true,
            "sourceSystem":"GOOGLE",
            "sourceMessageId":"<CAPGCw0SjBSTKGGJFwUWLyfVhZxxJV8e-TmNO0yz2xi0OzHOh8g@mail.gmail.com>",
            "sourceMessageFolder":"INBOX",
            "sourceMessageUID":"2",
            "isStarred":true,
            "inNetwork":false,
            "isBuddy":false,
            "ics":"",
            "sensitivity":"",
            "orderNum":1,
            "tags":[{
                    "id":1000,
                    "name":"Starred"
                }
            ]
        },
        {
            "messageId":219,
            "folderName":"UnifiedInbox",
            "type":1,
            "isThread":false,
            "threadLength":0,
            "draftLength":0,
            "deliveryStatusCode":0,
            "from":[{
                    "name":"Gmail Team",
                    "emailAddress":"mail-noreply@google.com"
                }
            ],
            "to":[{
                    "name":"bua plus",
                    "emailAddress":"buaplus@gmail.com"
                }
            ],
            "toParty":[],
            "cc":[],
            "subject":"Customize Gmail with colors and themes",
            "receivedDateShortTxt":"Mon, 03:06 PM",
            "receivedDate":"Mon Nov 21 15:06:54 EST 2011",
            "contactId":"",
            "attachment":false,
            "size":2,
            "priority":3,
            "answered":false,
            "draft":false,
            "read":false,
            "sourceSystem":"GOOGLE",
            "sourceMessageId":"<CAPGCw0QGS76tpnqpBM090BqOOWnBDXDVaEnuuajZ347NB57mvg@mail.gmail.com>",
            "sourceMessageFolder":"INBOX",
            "sourceMessageUID":"3",
            "isStarred":false,
            "inNetwork":false,
            "isBuddy":false,
            "ics":"",
            "sensitivity":"",
            "orderNum":1,
            "tags":[]
        },
        {
            "messageId":0,
            "folderName":"",
            "type":6,
            "isThread":false,
            "threadLength":0,
            "draftLength":0,
            "deliveryStatusCode":0,
            "from":[],
            "to":[],
            "toParty":[],
            "cc":[],
            "subject":"November 18th, 2011 Friday",
            "receivedDateShortTxt":"",
            "receivedDate":"",
            "contactId":"",
            "attachment":false,
            "size":0,
            "priority":0,
            "answered":false,
            "draft":false,
            "read":false,
            "sourceSystem":"",
            "sourceMessageId":"",
            "sourceMessageFolder":"",
            "sourceMessageUID":"",
            "isStarred":false,
            "inNetwork":false,
            "isBuddy":false,
            "ics":"",
            "sensitivity":"",
            "orderNum":0,
            "tags":[]
        },
        {
            "messageId":159,
            "folderName":"UnifiedInbox",
            "type":1,
            "isThread":true,
            "threadLength":37,
            "draftLength":0,
            "deliveryStatusCode":0,
            "from":[{
                    "name":"",
                    "emailAddress":"MAILER-DAEMON@yahoo.com"
                }
            ],
            "to":[{
                    "name":"",
                    "emailAddress":"icstesting@yahoo.com"
                },
                {
                    "name":"",
                    "emailAddress":"icstesting@yahoo.com"
                }
            ],
            "toParty":[],
            "cc":[],
            "subject":"Failure Notice",
            "receivedDateShortTxt":"Fri, 04:09 PM",
            "receivedDate":"Fri Nov 18 16:09:02 EST 2011",
            "contactId":"",
            "attachment":false,
            "size":5,
            "priority":3,
            "answered":false,
            "draft":false,
            "read":true,
            "sourceSystem":"YAHOO",
            "sourceMessageId":"",
            "sourceMessageFolder":"",
            "sourceMessageUID":"",
            "isStarred":false,
            "inNetwork":false,
            "isBuddy":false,
            "ics":"",
            "sensitivity":"",
            "orderNum":0,
            "tags":[]
        }
    ],
    "passwordChangeNotifications":[],
    "flags":{
        "showSyncPod":false,
        "errorMessage":"",
        "showSnglSyncPod":[]
    },
    "tags":[],
    "nabNotifications":[],
    "tagExceedNotifications":{
        "tagErrorMessage":""
    }
}