{
    "statusCode":0,
    "statusDesc":"Done",
    "isSlide":false,
    "unread":{
        "All":46,
        "email":5,
        "sms":41,
        "mms":0,
        "vvm":0,
        "call_log":0
    },
    "mailQuotaUsage":0,
    "messageId":1433,
    "composerId":"1327952403818",
    "replyMode":"W",
    "folderName":"Drafts",
    "vcard":false,
    "captionTxt":"",
    "displayImages":false,
    "receivedDate":"Today, 02:34 PM",
    "relativeTime":"Today, 02:34 PM (5 mins ago)",
    "receivedTimestamp":"Mon Jan 30 14:34:29 EST 2012",
    "type":2,
    "from":[{
            "name":"",
            "emailAddress":"9084187394"
        }
    ],
    "to":[{
            "name":"",
            "emailAddress":"6185347330"
        }
    ],
    "cc":[],
    "bcc":[],
    "replyTo":"9084187394",
    "replyFrom":"",
    "subject":"Text Message to (618)534-7330",
    "attachment":false,
    "contactId":"",
    "size":0,
    "priority":3,
    "answered":false,
    "draft":true,
    "read":true,
    "sourceSystem":"",
    "sourceMessageId":"",
    "sourceMessageUID":"",
    "sourceMessageFolder":"VDraft",
    "isStarred":false,
    "inNetwork":false,
    "isBuddy":false,
    "ics":"",
    "sensitivity":"",
    "isHTML":true,
    "body":"",
    "orderNum":0,
    "newContent":"",
    "oldContent":"",
    "tags":[],
    "attachmentList":[],
    "slideList":[],
    "isSendLater":false,
    "startTime":"",
    "endTime":"",
    "recurrenceType":""
}