




{"getContactsTime":0,"getMessageTime":0,"numRows":"","numDummyRows":0,"all":{"All":"","email":"","sms":"","mms":"","vvm":"","call_log":""},"unread":{"All":"","email":"","sms":"","mms":"","vvm":"","call_log":""},"undelivered":{"smsRowNums":"","mmsRowNums":"","isShow":"","smsItems":[],"mmsItems":[]},"statusCode":0,"statusDesc":"Done","items":[],"passwordChangeNotifications":[],"flags":{"showSyncPod":true,"errorMessage":""},"tags":[],"nabNotifications":[],"tagExceedNotifications":{"tagErrorMessage":""}}
