


{"statusCode":0,"statusDesc":"Signature details fetched successfully","numRows":1,"isSignatureEnabled":"","items":[{"title":"SNC","id":1,"signature":"<b><i><font color=\"#0000cd\">Send from Sync &amp; Connect<\/font><\/i><\/b>","isDefault":"1"}]}
