


{"identity":"id","statusCode":0,"statusDesc":"Tag Details fetched successfully","numRows":4,"items":[{"id":21584,"name":"Notes"},{"id":96111,"name":"Friends"},{"id":571501,"name":"[Gmail]/Important"},{"id":47850,"name":"important"}]}
