{
    "statusCode":0,
    "statusDesc":"Done",
    "media":[
    {
            "folder":"music",
            "size":"11.00",
            "percentage":5,
            "unit":"MB"
        },
        {
            "folder":"picture",
            "size":"23.00",
            "percentage":30,
            "unit":"MB"
        },
        {
            "folder":"video",
            "size":"15.00",
            "percentage":10,
            "unit":"MB"
        },
        {
            "folder":"document",
            "size":"100.00",
            "percentage":40,
            "unit":"MB"
        },{
            "folder":"total",
            "size":"500.00",
            "percentage":1,
            "unit":"MB"
        }
    ],
    "message":[{
            "folder":"email",
            "size":"5.22",
            "percentage":1,
            "unit":"MB"
        },
        {
            "folder":"text",
            "size":"8.30",
            "percentage":1,
            "unit":"KB"
        },
        {
            "folder":"total",
            "size":"16.23",
            "percentage":1,
            "unit":"MB"
        }
    ],
    "messagesRemaining":[{
            "folder":"remaining",
            "size":"1.98",
            "percentage":99,
            "unit":"GB"
        }
    ],
    "mediaRemaining":[{
            "folder":"remaining",
            "size":"450",
            "percentage":90,
            "unit":"MB"
        }
    ]
}