

{"statusCode":0,"statusDesc":"Done","fusionOne":true,"items":[{"group":"promo@e.newegg.com","contactId":"","valid":true,"groupLength":0,"isGroup":false,"validAddresses":[],"notValidContacts":[],"inNetwork":false}]}
